default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: forum_development
  username: postgres
  password: postgres
test:
  <<: *default
  database: forum_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: <%= ENV['FORUM_DATABASE_NAME'] %>
  username: <%= ENV['FORUM_DATABASE_USER'] %>
  password: <%= ENV['FORUM_DATABASE_PASSWORD'] %>